### ISSUE TITLE
API Issue with MaskFromRGBCMYBW node from Comfy Essentials

### ISSUE THREAD

**Issue by drommerkiller** [fofr/cog-comfyui#107]
When MaskFromRGBCMYBW node is used in workflow and tested with any-comfy in Replicate it works normally. But when same workflow is sent via api, it gives error: 

Executing node 21, title: 🔧 Mask From RGB/CMY/BW, class type: MaskFromRGBCMYBW+
!!! Exception during processing!!! MaskFromRGBCMYBW.execute() missing 2 required positional arguments: 'remove_isolated_pixels' and 'fill_holes'
Traceback (most recent call last):
File "/src/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/src/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/src/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: MaskFromRGBCMYBW.execute() missing 2 required positional arguments: 'remove_isolated_pixels' and 'fill_holes'

Those two missing arguments are something it creates in runtime. It seems that when any-comfy is called via API it handles runtime differently. I have tried to create various different workflows that have MaskFromRGBCMYBW node and result is always the same.

This is the first time that anything that works on any-comfy would not work via api.

**Comment by fofr** [comment]
Hmm, this seems odd, cc'ing @cubiq who might know more.

I can't see reference to those arguments on the latest version of the node here:
https://github.com/cubiq/ComfyUI_essentials/blob/4f2f11ca3c6f89e385bae8af739861f495e60540/mask.py#L418

**Comment by cubiq** [comment]
only explanation I could give is that either API uses an older version (precisely commit 4dcee21) or the workflow was saved with an older version and still has the reference at those 2 fields that were removed. Easy fix is to open the JSON file and remove the spurious values

**Comment by drommerkiller** [comment]
> only explanation I could give is that either API uses an older version (precisely commit 4dcee21) or the workflow was saved with an older version and still has the reference at those 2 fields that were removed. Easy fix is to open the JSON file and remove the spurious values

Thanks for the reply!
Where that those values should be in the api json?
Afaik this is the node:
  "44": {
    "inputs": {
      "threshold_r": 0.15,
      "threshold_g": 0.15,
      "threshold_b": 0.15,
      "image": [
        "31",
        0
      ]
    },
    "class_type": "MaskFromRGBCMYBW+",
    "_meta": {
      "title": "🔧 Mask From RGB/CMY/BW"
    }
  },
  
 So the json is made with the new version as it does not have those lines. API probably should use same commit than what is on replicate so can that be Replicate cache issue it still loading old version?

**Comment by drommerkiller** [comment]
Missclicked the close button, sorry.

**Comment by cubiq** [comment]
if the JSON file is updated, then the API is using an older version

**Comment by fofr** [comment]
https://github.com/fofr/cog-comfyui/blob/main/custom_nodes.json#L59-L60

This is the commit that's live – 5f1fc52, it's the SD3 negative conditioning one.

@drommerkiller please share some prediction links with error so I can see:

- model version you're running
- your json
- the error

**Comment by drommerkiller** [comment]
Sorry, this was then user error. I was calling earlier commit and did not figure that out as it didn't give error for missing node, but for the functionality of a node. This model version works now without the error: 075290da1227f68f144b33baaed36ed5a1f2c907dbad0584347b11b4b8ab7963

Sorry for wasting your time with this :(
