### ISSUE TITLE
Error downloading weights in ComfyUI/models/ultralytics/segm

### ISSUE THREAD

**Issue by bertagknowles** [fofr/cog-comfyui#126]
I am getting the following error when I run a json file. What could be the issue here?

Prediction failed.
Command '['pget', '--log-level', 'warn', '-xf', 'https://weights.replicate.delivery/default/comfy-ui/ultralytics/segm/hair_yolov8n-seg_60.pt.tar', 'ComfyUI/models/ultralytics/segm']' returned non-zero exit status 1.

Traceback:

Error: unexpected http status http://storagecache-ch-las1-3.storagecache-ch-las1.tenant-replicate-prdsvcs.svc.cluster.local/weights.replicate.delivery/default/comfy-ui/ultralytics/segm/hair_yolov8n-seg_60.pt.tar: 404 Not Found
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
File "/src/predict.py", line 105, in predict
wf = self.comfyUI.load_workflow(workflow_json or EXAMPLE_WORKFLOW_JSON)
File "/src/comfyui.py", line 216, in load_workflow
self.handle_weights(wf)
File "/src/comfyui.py", line 92, in handle_weights
self.weights_downloader.download_weights(weight)
File "/src/weights_downloader.py", line 39, in download_weights
self.download_if_not_exists(
File "/src/weights_downloader.py", line 60, in download_if_not_exists
WeightsDownloader.download(weight_str, url, dest)
File "/src/weights_downloader.py", line 71, in download
subprocess.check_call(
File "/root/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 369, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pget', '--log-level', 'warn', '-xf', 'https://weights.replicate.delivery/default/comfy-ui/ultralytics/segm/hair_yolov8n-seg_60.pt.tar', 'ComfyUI/models/ultralytics/segm']' returned non-zero exit status 1.

**Comment by bertagknowles** [comment]
Same error appearing after version update today: 

Checking weights
⏳ Downloading segm/hair_yolov8n-seg_60.pt to ComfyUI/models/ultralytics/segm
Error: unexpected http status http://storagecache-ch-ord1-3.storagecache-ch-ord1.tenant-replicate-prdsvcs.svc.cluster.local/weights.replicate.delivery/default/comfy-ui/ultralytics/segm/hair_yolov8n-seg_60.pt.tar: 404 Not Found

**Comment by fofr** [comment]
This should be working now, I've just pushed a fix:

https://weights.replicate.delivery/default/comfy-ui/ultralytics/segm/hair_yolov8n-seg_60.pt.tar

**Comment by bertagknowles** [comment]
Great! Thanks for the quick resolution. 

I have another question. I would like to pass the input images in base64 format from my application. However comfyui does not seem to accept this _(Failed to validate prompt for output 144: * LoadImage 134:
- Custom validation failed for node: image - Invalid image file: http://data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEBLAEsAAD/4Y5WRXhpZgAATU0AKgAAAAgACg......)_

Is there any way that it can accept the image without hosting the image somewhere? I know for sure that replicate api accepts base64 image format as it accepts for other models. It would be great if the replicate interface has option for 2 input images instead of only one. Since sending images as zip file from my app through api does not seem feasible.  Therefore I use base64 embedded inside the url to send image through api.

**Comment by fofr** [comment]
If you pass in the image as `file` in the API call, and in your workflow refer to `input.jpeg` that should work.

**Comment by fofr** [comment]
Closing this issue now as it is fixed, but feel free to reply/open another issue.
