### ISSUE TITLE
InstantX Flux Union ControlNet Loader does not exist.

### ISSUE THREAD

**Issue by nick19a** [fofr/cog-comfyui#156]
I thought the "InstantX Flux Union ControlNet Loader" node was supported?

```

====================================
Inputs uploaded to /tmp/inputs:
input.jpg
====================================
Checking inputs
❌ /tmp/inputs/image.jpg not provided
====================================
Checking weights
⏳ Downloading clip_l.safetensors to ComfyUI/models/clip
✅ clip_l.safetensors downloaded to ComfyUI/models/clip in 0.32s, size: 234.74MB
⏳ Downloading flux1-dev.safetensors to ComfyUI/models/unet
✅ flux1-dev.safetensors downloaded to ComfyUI/models/unet in 10.98s, size: 22700.25MB
⏳ Downloading t5xxl_fp16.safetensors to ComfyUI/models/clip
✅ t5xxl_fp16.safetensors downloaded to ComfyUI/models/clip in 6.22s, size: 9334.41MB
✅ lora.safetensors exists in ComfyUI/models/loras
⏳ Downloading FLUX.1-dev-ControlNet-Union-Pro.safetensors to ComfyUI/models/controlnet
✅ FLUX.1-dev-ControlNet-Union-Pro.safetensors downloaded to ComfyUI/models/controlnet in 57.97s, size: 6298.02MB
⏳ Downloading ae.safetensors to ComfyUI/models/vae
✅ ae.safetensors downloaded to ComfyUI/models/vae in 0.41s, size: 319.77MB
====================================
Randomising noise_seed to 2884434922
Running workflow
got prompt
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node InstantX Flux Union ControlNet Loader does not exist.', 'details': "Node ID '#43'", 'extra_info': {}}
ComfyUI error: 400 Bad Request
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cog/server/worker.py", line 354, in _predict
result = predict(**payload)
File "/src/predict.py", line 115, in predict
self.comfyUI.run_workflow(wf)
File "/src/comfyui.py", line 242, in run_workflow
prompt_id = self.queue_prompt(workflow)
File "/src/comfyui.py", line 180, in queue_prompt
raise Exception(
Exception: ComfyUI Error – Your workflow could not be run. This usually happens if you’re trying to use an unsupported node. Check the logs for 'KeyError: ' details, and go to https://github.com/fofr/cog-comfyui to see the list of supported custom nodes.

```

![image](https://github.com/user-attachments/assets/8fff4ea2-d1c5-4a62-8849-87f585b3bdba)

**Comment by fofr** [comment]
Is this working now?

**Comment by fofr** [comment]
The InstantX loaders are now supported directly in ComfyUI, these custom nodes have been removed and the Replicate model updated.
