### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Inner-Reflections** [fofr/cog-comfyui#19]
====================================
Inputs uploaded to /tmp/inputs:
Input.MOV
====================================
Checking weights
✅ ZoeD_M12_N.pt
✅ control_v11f1p_sd15_depth.pth
✅ sd15_t2v_beta.ckpt
✅ lcm-lora-sdv1-5.safetensors
✅ vae-ft-mse-840000-ema-pruned.safetensors
✅ Realistic_Vision_V5.1.safetensors
====================================
Checking inputs
====================================
Running workflow
got prompt
Error handling request
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/src/ComfyUI/server.py", line 47, in cache_control
response: web.Response = await handler(request)
File "/src/ComfyUI/server.py", line 474, in post_prompt
valid = execution.validate_prompt(prompt)
File "/src/ComfyUI/execution.py", line 620, in validate_prompt
class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'ADE_LoadAnimateDiffModel'
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "/src/predict.py", line 94, in predict
self.comfyUI.run_workflow(wf)
File "/src/helpers/comfyui.py", line 213, in run_workflow
prompt_id = self.queue_prompt(workflow)
File "/src/helpers/comfyui.py", line 150, in queue_prompt
output = json.loads(urllib.request.urlopen(req).read())
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 216, in urlopen
return opener.open(url, data, timeout)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 525, in open
response = meth(req, response)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 634, in http_response
response = self.parent.error(
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 563, in error
return self._call_chain(*args)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 496, in _call_chain
result = func(*args)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 643, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

trying to run an LCM AnimateDiff workflow - Not sure what I am doing wrong here.

**Comment by fofr** [comment]
Do you have a link to your prediction, I'll take a look

**Comment by Inner-Reflections** [comment]
Sorry what link are you looking for exactly? The workflow or something else?

**Comment by fofr** [comment]
Ah, when you get an error, you can share the link:

<img width="516" alt="Screenshot 2024-02-16 at 21 50 23" src="https://github.com/fofr/cog-comfyui/assets/319055/a8f5f7d0-45f4-4a76-a834-2f67edfa7503">

**Comment by fofr** [comment]
Alternatively, share your workflow/inputs and I can take it from there

**Comment by Inner-Reflections** [comment]
https://replicate.com/p/qfbehudbv55wdmvwn4zqcb2xoa

**Comment by fofr** [comment]
Ahh, I think the issue here is from the big refactor and new version (https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/pull/281)

The custom node in this repo is currently pinned to commit d2bf367, which doesn't support ADE_LoadAnimateDiffModel.

The fix will be to upgrade this custom node to the latest version.

**Comment by fofr** [comment]
I will upgrade when this is resolved:
https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/pull/303

(I don't want to add a GitPython dependency)

**Comment by fofr** [comment]
This is all working now:
https://replicate.com/p/5m2zl53bmpqox36mh26o7tlvli

(I had to tweak your workflow from `input.mov` to `Input.MOV` as it is case sensitive)
