### ISSUE TITLE
There are a lot of errors in Setup logs

### ISSUE THREAD

**Issue by chargenius** [fofr/cog-comfyui#229]
[fofr](https://replicate.com/fofr) /[any-comfyui-workflow](https://replicate.com/fofr/any-comfyui-workflow)

error Logs:
```
Error while loading predictor:

Traceback (most recent call last):
  File "/srv/r8/monobase/cog/g1df235d5/cog0.13.6-python3.10/lib/python3.10/site-packages/cog/server/http.py", line 159, in create_app
    InputType, OutputType, is_async = cog_config.get_predictor_types(
  File "/srv/r8/monobase/cog/g1df235d5/cog0.13.6-python3.10/lib/python3.10/site-packages/cog/config.py", line 164, in get_predictor_types
    predictor = self._load_predictor_for_types(
  File "/srv/r8/monobase/cog/g1df235d5/cog0.13.6-python3.10/lib/python3.10/site-packages/cog/config.py", line 140, in _load_predictor_for_types
    module = load_full_predictor_from_file(module_path, module_name)
  File "/srv/r8/monobase/cog/g1df235d5/cog0.13.6-python3.10/lib/python3.10/site-packages/cog/predictor.py", line 148, in load_full_predictor_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/src/predict.py'
```

**Comment by fofr** [comment]
How are you running this?

**Comment by fofr** [comment]
This is a wider infra issue, I think it'll be resolved independently of this repo
