### ISSUE TITLE
Failure to download a file before running my workflow

### ISSUE THREAD

**Issue by devoln** [fofr/cog-comfyui#232]
When I run my workflow [comfy-workflow-api.json](https://github.com/user-attachments/files/18222689/comfy-workflow-api.json) on Replicate using version `d485be22dbc`, I get an error:

> Prediction failed.
> 
> Command '['pget', '--log-level', 'warn', '-xf', 'https://weights.replicate.delivery/default/comfy-ui/facedetection/detection_Resnet50_Final.pth.tar', '/srv/r8/monobase/monobase/g00012/python3.10-torch2.5.1-cu121/lib/python3.10/site-packages/facexlib/weights']' returned non-zero exit status 1.

Logs:

```
Error: error writing file: error extracting file: mkdir /srv/r8/monobase/monobase/g00012/python3.10-torch2.5.1-cu121/lib/python3.10/site-packages/facexlib: read-only file system
Traceback (most recent call last):
File "/srv/r8/monobase/cog/g1df235d5/cog0.13.6-python3.10/lib/python3.10/site-packages/cog/server/worker.py", line 646, in _handle_predict_error
yield
File "/srv/r8/monobase/cog/g1df235d5/cog0.13.6-python3.10/lib/python3.10/site-packages/cog/server/worker.py", line 538, in _predict
result = predict(**payload)
File "/src/predict.py", line 127, in predict
wf = self.comfyUI.load_workflow(workflow_json or EXAMPLE_WORKFLOW_JSON)
File "/src/comfyui.py", line 275, in load_workflow
self.handle_weights(wf)
File "/src/comfyui.py", line 98, in handle_weights
self.apply_helper_methods("add_weights", weights_to_download, Node(node))
File "/src/comfyui.py", line 86, in apply_helper_methods
method(*args, **kwargs)
File "/src/custom_node_helpers/PuLID.py", line 41, in add_weights
weights_downloader.download_if_not_exists(
File "/src/weights_downloader.py", line 61, in download_if_not_exists
WeightsDownloader.download(weight_str, url, dest)
File "/src/weights_downloader.py", line 72, in download
subprocess.check_call(
File "/srv/r8/monobase/uv/python/cpython-3.10.15-linux-x86_64-gnu/lib/python3.10/subprocess.py", line 369, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pget', '--log-level', 'warn', '-xf', 'https://weights.replicate.delivery/default/comfy-ui/facedetection/detection_Resnet50_Final.pth.tar', '/srv/r8/monobase/monobase/g00012/python3.10-torch2.5.1-cu121/lib/python3.10/site-packages/facexlib/weights']' returned non-zero exit status 1.
====================================
Inputs uploaded to /tmp/inputs:
input.jpg
====================================
Checking inputs
✅ /tmp/inputs/input.jpg
====================================
Checking weights
Adding ltx-video-2b-v0.9.1.safetensors to CHECKPOINTS
Adding realvisxlV50_v50Bakedvae.safetensors to CHECKPOINTS
Adding CN-anytest_v3-50000_fp16.safetensors to CONTROLNET
Adding CogFlorence-2.1-Large to LLM
Adding CogFlorence-2.2-Large to LLM
Adding Florence-2-base to LLM
Adding Florence-2-base-ft to LLM
Adding Florence-2-base-PromptGen-v1.5 to LLM
Adding Florence-2-base-PromptGen-v2.0 to LLM
Adding Florence-2-DocVQA to LLM
Adding Florence-2-Flux-Large to LLM
Adding Florence-2-large to LLM
Adding Florence-2-large-ft to LLM
Adding Florence-2-large-PromptGen-v1.5 to LLM
Adding Florence-2-large-PromptGen-v2.0 to LLM
Adding Florence-2-SD3-Captioner to LLM
⏳ Downloading detection_Resnet50_Final.pth to /srv/r8/monobase/monobase/g00012/python3.10-torch2.5.1-cu121/lib/python3.10/site-packages/facexlib/weights
```

I guess that tjis dependency on detection_Resnet50_Final is added by one of the PULID nodes that I use with FLUX. If I remove PULID nodes from my workflow, it works. Actually, I don't understand the error. The file URL is accessible, I can download it manually.

**Comment by redstarxz** [comment]
I encountered the same problem.  i don't know why it download detection_Resnet50_Final.pth to a special path (which is read only)

**Comment by fofr** [comment]
I'm investigating this

**Comment by fofr** [comment]
I've identified the cause, still working on a fix.

**Comment by fofr** [comment]
I have fixed this by replacing the PuLID flux custom nodes with a newer one (with the same node names):

As recommended in #246 – this uses facexlib models in the ComfyUI/models/facexlib directory.

I've also added support for pulid v0.9.1 for flux

**Comment by fofr** [comment]
@devoln Your workflow runs as expected now

https://replicate.com/p/y5b5ms7zx1rm80cmnk4ae1a164
