### ISSUE TITLE
Replicate Run error

### ISSUE THREAD

**Issue by bestofajith** [fofr/cog-comfyui#30]
Hi, Do you know why I got this error?

File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 643, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

Best

**Comment by fofr** [comment]
Can you post the full error? I think it'll likely be you're trying to use an unsupported node

**Comment by bestofajith** [comment]
> Can you post the full error? I think it'll likely be you're trying to use an unsupported node

This is the full report.
====================================
Randomising seed to 4185295363
Running workflow
got prompt
Error handling request
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/src/ComfyUI/server.py", line 47, in cache_control
response: web.Response = await handler(request)
File "/src/ComfyUI/server.py", line 474, in post_prompt
valid = execution.validate_prompt(prompt)
File "/src/ComfyUI/execution.py", line 620, in validate_prompt
class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'EmbeddingPicker'
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "/src/predict.py", line 94, in predict
self.comfyUI.run_workflow(wf)
File "/src/helpers/comfyui.py", line 224, in run_workflow
prompt_id = self.queue_prompt(workflow)
File "/src/helpers/comfyui.py", line 160, in queue_prompt
output = json.loads(urllib.request.urlopen(req).read())
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 216, in urlopen
return opener.open(url, data, timeout)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 525, in open
response = meth(req, response)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 634, in http_response
response = self.parent.error(
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 563, in error
return self._call_chain(*args)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 496, in _call_chain
result = func(*args)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 643, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by bestofajith** [comment]
I'm using 'Appy IPAdapter FaceID' from IPAdapter, does that make the error?
