### ISSUE TITLE
Error running UltimateSDUpscale

### ISSUE THREAD

**Issue by mspurr** [fofr/cog-comfyui#40]
I am getting empty outputs when using UltimateSDUpscale. Here is the replicate logs:

```
Checking inputs
====================================
Checking weights
⏳ Downloading juggernautXL_v8Rundiffusion.safetensors to ComfyUI/models/checkpoints
⌛️ Downloaded juggernautXL_v8Rundiffusion.safetensors in 30.40s, size: 6776.19MB
✅ juggernautXL_v8Rundiffusion.safetensors
⏳ Downloading 4x_NMKD-Siax_200k.pth to ComfyUI/models/upscale_models
⌛️ Downloaded 4x_NMKD-Siax_200k.pth in 0.03s, size: 0.05MB
✅ 4x_NMKD-Siax_200k.pth
====================================
Randomising seed to 150777435
Randomising seed to 1634076115
Running workflow
got prompt
Executing node 2, title: Load Checkpoint, class type: CheckpointLoaderSimple
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Executing node 4, title: positive prompt, class type: CLIPTextEncode
Requested to load SDXLClipModel
Loading 1 new model
Executing node 5, title: negative prompt, class type: CLIPTextEncode
Executing node 6, title: Empty Latent Image, class type: EmptyLatentImage
Executing node 1, title: KSampler, class type: KSampler
Requested to load SDXL
Loading 1 new model
  0%|          | 0/18 [00:00<?, ?it/s]
  6%|▌         | 1/18 [00:00<00:14,  1.16it/s]
 11%|█         | 2/18 [00:01<00:09,  1.65it/s]
 17%|█▋        | 3/18 [00:01<00:07,  1.90it/s]
 22%|██▏       | 4/18 [00:02<00:06,  2.06it/s]
 28%|██▊       | 5/18 [00:02<00:06,  2.15it/s]
 33%|███▎      | 6/18 [00:02<00:05,  2.21it/s]
 39%|███▉      | 7/18 [00:03<00:04,  2.25it/s]
 44%|████▍     | 8/18 [00:03<00:04,  2.26it/s]
 50%|█████     | 9/18 [00:04<00:03,  2.28it/s]
 56%|█████▌    | 10/18 [00:04<00:03,  2.30it/s]
 61%|██████    | 11/18 [00:05<00:03,  2.33it/s]
 67%|██████▋   | 12/18 [00:05<00:02,  2.34it/s]
 72%|███████▏  | 13/18 [00:06<00:02,  2.32it/s]
 78%|███████▊  | 14/18 [00:06<00:01,  2.35it/s]
 83%|████████▎ | 15/18 [00:06<00:01,  2.40it/s]
 89%|████████▉ | 16/18 [00:07<00:00,  2.43it/s]
 94%|█████████▍| 17/18 [00:07<00:00,  2.48it/s]
100%|██████████| 18/18 [00:07<00:00,  2.97it/s]
100%|██████████| 18/18 [00:07<00:00,  2.31it/s]
Requested to load AutoencoderKL
Loading 1 new model
Executing node 7, title: VAE Decode, class type: VAEDecode
Executing node 25, title: Load Upscale Model, class type: UpscaleModelLoader
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
File "/src/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/src/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/src/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/src/ComfyUI/comfy_extras/nodes_upscale_model.py", line 20, in load_model
sd = comfy.utils.load_torch_file(model_path, safe_load=True)
File "/src/ComfyUI/custom_nodes/ComfyUI-PhotoMaker/.patches.py", line 12, in load_torch_file
pl_sd = torch.load(ckpt, map_location=device, weights_only=True)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/serialization.py", line 1039, in load
raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 60
Prompt executed in 12.80 seconds
outputs:  {}
====================================
Contents of /tmp/outputs:
```

And here is the workflow:

```{"1":{"inputs":{"seed":315482209324445,"steps":18,"cfg":2,"sampler_name":"dpmpp_sde","scheduler":"karras","denoise":1,"model":["2",0],"positive":["4",0],"negative":["5",0],"latent_image":["6",0]},"class_type":"KSampler","_meta":{"title":"KSampler"}},"2":{"inputs":{"ckpt_name":"juggernautXL_v8Rundiffusion.safetensors"},"class_type":"CheckpointLoaderSimple","_meta":{"title":"Load Checkpoint"}},"4":{"inputs":{"text":"A beautiful portrait photograph of a dragon with dark black scales, opal eyes, smoke out of nose, cinematic, detailed scales, fantasy art, hyperdetailed photograph, matte dark scales, 8k resolution,","clip":["2",1]},"class_type":"CLIPTextEncode","_meta":{"title":"positive prompt"}},"5":{"inputs":{"text":"","clip":["2",1]},"class_type":"CLIPTextEncode","_meta":{"title":"negative prompt"}},"6":{"inputs":{"width":1216,"height":832,"batch_size":1},"class_type":"EmptyLatentImage","_meta":{"title":"Empty Latent Image"}},"7":{"inputs":{"samples":["1",0],"vae":["2",2]},"class_type":"VAEDecode","_meta":{"title":"VAE Decode"}},"25":{"inputs":{"model_name":"4x_NMKD-Siax_200k.pth"},"class_type":"UpscaleModelLoader","_meta":{"title":"Load Upscale Model"}},"27":{"inputs":{"upscale_by":1.5,"seed":-1,"steps":15,"cfg":2,"sampler_name":"dpmpp_sde","scheduler":"karras","denoise":0.3,"mode_type":"Linear","tile_width":1216,"tile_height":832,"mask_blur":8,"tile_padding":32,"seam_fix_mode":"None","seam_fix_denoise":1,"seam_fix_width":64,"seam_fix_mask_blur":8,"seam_fix_padding":16,"force_uniform_tiles":true,"tiled_decode":false,"image":["7",0],"model":["2",0],"positive":["4",0],"negative":["5",0],"vae":["2",2],"upscale_model":["25",0]},"class_type":"UltimateSDUpscale","_meta":{"title":"Ultimate SD Upscale"}},"28":{"inputs":{"filename_prefix":"createit","images":["27",0]},"class_type":"SaveImage","_meta":{"title":"Save Image"}}}```

Any idea what is going wrong?
Thanks

**Comment by fofr** [comment]
That's odd, do you have the UI version I can see in ComfyUI to see if there's any issues there?

**Comment by fofr** [comment]
It seems like it's an issue with the upscale model not loading correctly. Your workflow works correctly with `RealESRGAN_x4.pth`.

https://replicate.com/p/tsezbntb3v32f26nfpsnovn5kq

**Comment by fofr** [comment]
Closing this for now, but if this is still happening feel free to reopen.

**Comment by rovillanueva** [comment]
Hi! I'm using the workflow on Replicate and trying to use 4x_NMKD-Siax_200k.pth for upscaling, as it's listed in supported_weights.md. However, the prediction fails with a `_pickle.UnpicklingError` due to PyTorch 2.6 defaulting to `weights_only=True`.

Is there anything you can do about it?
I find the 4x_NMKD-Siax_200k the best upscaler for my images.
Thank you for your support!

```
Full error message:
There was an error executing your workflow: { "type": "execution_error", "data": { "prompt_id": "6e3a998d-da83-41fc-861e-62a390c2ea84", "node_id": "12", "node_type": "UpscaleModelLoader", "executed": [], "exception_message": "Weights only load failed. In PyTorch 2.6, we changed the default value of the weights_only argument in torch.load from False to True. Re-running torch.load with weights_only set to False will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.\nPlease file an issue with the following so that we can make weights_only=True compatible with your use case: WeightsUnpickler error: Unsupported operand 60\n\nCheck the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.\n", "exception_type": "_pickle.UnpicklingError", "traceback": [ " File \"/src/ComfyUI/execution.py\", line 427, in execute\n output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", " File \"/src/ComfyUI/execution.py\", line 270, in get_output_data\n return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", " File \"/src/ComfyUI/execution.py\", line 244, in _async_map_node_over_list\n await process_inputs(input_dict, i)\n", " File \"/src/ComfyUI/execution.py\", line 232, in process_inputs\n result = f(**inputs)\n ^^^^^^^^^^^\n", " File \"/src/ComfyUI/comfy_extras/nodes_upscale_model.py\", line 28, in load_model\n sd = comfy.utils.load_torch_file(model_path, safe_load=True)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", " File \"/src/ComfyUI/comfy/utils.py\", line 82, in load_torch_file\n pl_sd = torch.load(ckpt, map_location=device, weights_only=True, **torch_args)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", " File \"/root/.pyenv/versions/3.12.11/lib/python3.12/site-packages/torch/serialization.py\", line 1548, in load\n raise pickle.UnpicklingError(_get_wo_message(str(e))) from None\n" ], "current_inputs": { "model_name": [ "4x_NMKD-Siax_200k.pth" ] }, "current_outputs": [ "18", "56", "14", "10", "44", "55", "66", "12", "47", "67", "45", "3", "68" ], "timestamp": 1754467773720 } }
```

```
Here's my workflow:
{
  "3": {
    "inputs": {
      "width": 1024,
      "height": 1024,
      "batch_size": 1
    },
    "class_type": "EmptyLatentImage",
    "_meta": {
      "title": "Empty Latent Image"
    }
  },
  "10": {
    "inputs": {
      "samples": [
        "18",
        0
      ],
      "vae": [
        "14",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "12": {
    "inputs": {
      "model_name": "4x_NMKD-Siax_200k.pth"
    },
    "class_type": "UpscaleModelLoader",
    "_meta": {
      "title": "Load Upscale Model"
    }
  },
  "14": {
    "inputs": {
      "ckpt_name": "realismEngineSDXL_v30VAE.safetensors"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "18": {
    "inputs": {
      "seed": 476789937772479,
      "steps": 40,
      "cfg": 2,
      "sampler_name": "dpmpp_3m_sde",
      "scheduler": "karras",
      "denoise": 1,
      "model": [
        "66",
        0
      ],
      "positive": [
        "45",
        0
      ],
      "negative": [
        "44",
        0
      ],
      "latent_image": [
        "3",
        0
      ]
    },
    "class_type": "KSampler",
    "_meta": {
      "title": "KSampler"
    }
  },
  "44": {
    "inputs": {
      "text": "(worst quality, low quality), deformed, open mouth, nsfw, nude, nudity, porn, naked, blurry, artifacts",
      "clip": [
        "66",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "NEGATIVE PROMPT GENERATION"
    }
  },
  "45": {
    "inputs": {
      "text": "Opulent master bedroom designed for ultimate comfort: king‑size bed with tufted headboard by Minotti, high‑gloss lacquered wardrobe, warm hardwood floor, and soft natural lighting through large windows",
      "clip": [
        "66",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "POSITIVE PROMPT GENERATION"
    }
  },
  "47": {
    "inputs": {
      "upscale_by": 2,
      "seed": 721310777630374,
      "steps": 20,
      "cfg": 2,
      "sampler_name": "dpmpp_3m_sde",
      "scheduler": "karras",
      "denoise": 0.4000000000000001,
      "mode_type": "Linear",
      "tile_width": 1024,
      "tile_height": 1024,
      "mask_blur": 16,
      "tile_padding": 32,
      "seam_fix_mode": "None",
      "seam_fix_denoise": 1,
      "seam_fix_width": 64,
      "seam_fix_mask_blur": 8,
      "seam_fix_padding": 16,
      "force_uniform_tiles": true,
      "tiled_decode": false,
      "image": [
        "10",
        0
      ],
      "model": [
        "67",
        0
      ],
      "positive": [
        "55",
        0
      ],
      "negative": [
        "56",
        0
      ],
      "vae": [
        "14",
        2
      ],
      "upscale_model": [
        "12",
        0
      ]
    },
    "class_type": "UltimateSDUpscale",
    "_meta": {
      "title": "Ultimate SD Upscale"
    }
  },
  "55": {
    "inputs": {
      "text": "Opulent master bedroom designed for ultimate comfort: king‑size bed with tufted headboard by Minotti, high‑gloss lacquered wardrobe, warm hardwood floor, and soft natural lighting through large windows",
      "clip": [
        "67",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "POSITIVE PROMPT UPSCALE"
    }
  },
  "56": {
    "inputs": {
      "text": "(worst quality, low quality), deformed, open mouth, nsfw, nude, nudity, porn, naked, blurry, artifacts",
      "clip": [
        "67",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "NEGATIVE PROMPT UPSCALE"
    }
  },
  "66": {
    "inputs": {
      "lora_name": "add-detail-xl.safetensors",
      "strength_model": 0.30000000000000004,
      "strength_clip": 1,
      "model": [
        "14",
        0
      ],
      "clip": [
        "14",
        1
      ]
    },
    "class_type": "LoraLoader",
    "_meta": {
      "title": "Load LoRA"
    }
  },
  "67": {
    "inputs": {
      "lora_name": "add-detail-xl.safetensors",
      "strength_model": 0.7000000000000002,
      "strength_clip": 1,
      "model": [
        "14",
        0
      ],
      "clip": [
        "14",
        1
      ]
    },
    "class_type": "LoraLoader",
    "_meta": {
      "title": "Load LoRA"
    }
  },
  "68": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "47",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  }
}
```
