### ISSUE TITLE
Motion  Lora Load Issue

### ISSUE THREAD

**Issue by DrakenZA** [fofr/cog-comfyui#74]
I edited the weights_downloader to skip custom models i put in the docker. Works fine for the sd checkpoint.

But for some reason, when i try use a motion lora, the cog does something really strange
```

Executing node 43, title: Load AnimateDiff LoRA 🎭🅐🅓, class type: ADE_AnimateDiffLoRALoader
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
File "/src/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/src/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/src/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/src/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/nodes_lora.py", line 36, in load_motion_lora
if not Path(lora_path).is_file():
File "/root/.pyenv/versions/3.10.6/lib/python3.10/pathlib.py", line 960, in __new__
self = cls._from_parts(args)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/pathlib.py", line 594, in _from_parts
drv, root, parts = self._parse_args(args)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/pathlib.py", line 578, in _parse_args
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Its as if the json contained nothing in the lora_name parameter. But as you can see here..

```
  "43": {
    "inputs": {
      "lora_name": "Draken_Motion_Lora.safetensors",
      "strength": 0.25
    },
    "class_type": "ADE_AnimateDiffLoRALoader",
    "_meta": {
      "title": "Load AnimateDiff LoRA 🎭🅐🅓"
    }
  },
  ```
  
and the file is in the correct motion_lora folder in Animatediff CustomNode inside the docker image, confirmed before i pushed but bashing into the cog like your repo suggests.

Would be really helpful if you have any idea. Thank you for your work.

**Comment by DrakenZA** [comment]
I also started up comfyui inside the docker, and the motion lora is present in the loader node.

I can only assume some part of the predict code is replacing the lora name or something cause its not on a list somewhere ??

**Comment by fofr** [comment]
Closing this as I think you resolved following Discord conversation.
